/**
 * A validated `oiml-r76-1-2006` rule pack for the engine's own test suite.
 *
 * The engine has zero internal package imports — even in tests — so this is
 * a self-contained copy of `packages/rulepacks/data/oiml-r76-1-2006/rulepack.json`,
 * run through the engine's own `loadRulepack`. Keep the two in sync; the
 * `@tula/rulepacks` package tests (index.test.ts there) guard the real file
 * independently.
 */
import { loadRulepack, type Rulepack } from '../rulepack.js';

const RAW_RULEPACK = {
  id: 'oiml-r76-1-2006',
  version: '1.0.0',
  title: 'OIML R 76-1:2006 / R 76-2:2007',

  classification: {
    I: [{ eMin: '0.001', nMin: 50000, minE: 100 }],
    II: [
      { eMin: '0.001', eMax: '0.05', nMin: 100, nMax: 100000, minE: 20 },
      { eMin: '0.1', nMin: 5000, nMax: 100000, minE: 50 },
    ],
    III: [
      { eMin: '0.1', eMax: '2', nMin: 100, nMax: 10000, minE: 20 },
      { eMin: '5', nMin: 500, nMax: 10000, minE: 20 },
    ],
    IIII: [{ eMin: '5', nMin: 100, nMax: 1000, minE: 10 }],
  },

  mpeBands: {
    I: [
      { upToE: 50000, mpeE: '0.5' },
      { upToE: 200000, mpeE: '1.0' },
      { upToE: null, mpeE: '1.5' },
    ],
    II: [
      { upToE: 5000, mpeE: '0.5' },
      { upToE: 20000, mpeE: '1.0' },
      { upToE: null, mpeE: '1.5' },
    ],
    III: [
      { upToE: 500, mpeE: '0.5' },
      { upToE: 2000, mpeE: '1.0' },
      { upToE: null, mpeE: '1.5' },
    ],
    IIII: [
      { upToE: 50, mpeE: '0.5' },
      { upToE: 200, mpeE: '1.0' },
      { upToE: null, mpeE: '1.5' },
    ],
  },

  inServiceFactor: 2,

  tests: [
    {
      code: 'EXAM_MARKINGS',
      evaluator: 'examMarkings@1',
      title: 'Descriptive markings',
      clause: '7.1',
      applicability: { always: true },
      params: {},
      mvp: true,
    },
    {
      code: 'EXAM_CONSTRUCTION',
      evaluator: 'examConstruction@1',
      title: 'Construction, sealing and software identification',
      clause: '3.10',
      applicability: { always: true },
      params: {},
      mvp: true,
    },
    {
      code: 'ZERO_RANGE',
      evaluator: 'zeroRange@1',
      title: 'Zero-setting range',
      clause: '4.5.1',
      applicability: { always: true },
      params: {},
      mvp: false,
    },
    {
      code: 'ZERO_ACCURACY',
      evaluator: 'zeroAccuracy@1',
      title: 'Accuracy of zero-setting',
      clause: '4.5.2',
      applicability: { always: true },
      params: {},
      mvp: true,
    },
    {
      code: 'ZERO_TRACKING',
      evaluator: 'zeroTracking@1',
      title: 'Zero-tracking',
      clause: '4.5',
      applicability: { requires: ['hasZeroTracking'] },
      params: {},
      mvp: false,
    },
    {
      code: 'WEIGHING',
      evaluator: 'weighing@1',
      title: 'Weighing test, ascending and descending',
      clause: '3.5.1, 3.5.3',
      applicability: { always: true },
      params: { minLoads: 5, stepFractionOfE: '0.1' },
      mvp: true,
    },
    {
      code: 'WEIGHING_SUPPL',
      evaluator: 'weighingSuppl@1',
      title: 'Supplementary weighing test',
      clause: 'Annex A',
      applicability: { requires: ['initialZeroSettingExceeds20Pct'] },
      params: {},
      mvp: false,
    },
    {
      code: 'ECCENTRICITY',
      evaluator: 'eccentricity@1',
      title: 'Eccentric loading',
      clause: '3.6.2',
      applicability: { always: true },
      params: {},
      mvp: true,
    },
    {
      code: 'DISCRIMINATION',
      evaluator: 'discrimination@1',
      title: 'Discrimination',
      clause: '3.8',
      applicability: { always: true },
      params: {},
      mvp: true,
    },
    {
      code: 'REPEATABILITY',
      evaluator: 'repeatability@1',
      title: 'Repeatability',
      clause: '3.6.1',
      applicability: { always: true },
      params: {},
      mvp: true,
    },
    {
      code: 'TARE_ACCURACY',
      evaluator: 'tareAccuracy@1',
      title: 'Accuracy of the tare device',
      clause: '4.6',
      applicability: { requires: ['hasTareDevice'] },
      params: {},
      mvp: false,
    },
    {
      code: 'WEIGHING_TARE',
      evaluator: 'weighingTare@1',
      title: 'Weighing test with tare',
      clause: '3.5.3.3',
      applicability: { requires: ['hasTareDevice'] },
      params: {},
      mvp: false,
    },
    {
      code: 'TILTING',
      evaluator: 'tilting@1',
      title: 'Tilting',
      clause: '3.9.1',
      applicability: { classes: ['II', 'III', 'IIII'], requires: ['tiltSusceptible'] },
      params: {},
      mvp: false,
    },
    {
      code: 'WARM_UP',
      evaluator: 'warmUp@1',
      title: 'Warm-up time',
      clause: '5',
      applicability: { requires: ['isElectronic'] },
      params: {},
      mvp: false,
    },
    {
      code: 'TEMP_STATIC',
      evaluator: 'tempStatic@1',
      title: 'Static temperatures',
      clause: '3.9.2.1-3.9.2.2',
      applicability: { always: true },
      params: {},
      mvp: false,
    },
    {
      code: 'TEMP_NO_LOAD',
      evaluator: 'tempNoLoad@1',
      title: 'Temperature effect on no-load indication',
      clause: '3.9.2.3',
      applicability: { always: true },
      params: {},
      mvp: true,
    },
    {
      code: 'DAMP_HEAT',
      evaluator: 'dampHeat@1',
      title: 'Damp heat, steady state',
      clause: 'Annex B',
      applicability: { requires: ['isElectronic'] },
      params: {},
      mvp: false,
    },
    {
      code: 'POWER_SUPPLY',
      evaluator: 'powerSupply@1',
      title: 'Power supply variations',
      clause: '3.9.3',
      applicability: { requires: ['isElectronic'] },
      params: {},
      mvp: false,
    },
    {
      code: 'CREEP',
      evaluator: 'creep@1',
      title: 'Variation of indication with time (creep)',
      clause: '3.9.4.1',
      applicability: { classes: ['II', 'III', 'IIII'] },
      params: {},
      mvp: true,
    },
    {
      code: 'ZERO_RETURN',
      evaluator: 'zeroReturn@1',
      title: 'Zero return after 30 min load',
      clause: '3.9.4.2',
      applicability: { classes: ['II', 'III', 'IIII'] },
      params: {},
      mvp: true,
    },
    {
      code: 'DURABILITY',
      evaluator: 'durability@1',
      title: 'Durability',
      clause: '3.9.4.3',
      applicability: { classes: ['II', 'III', 'IIII'], requires: ['maxAtMost100kg'] },
      params: {},
      mvp: false,
    },
    {
      code: 'DISTURBANCES',
      evaluator: 'disturbances@1',
      title: 'Electromagnetic disturbances',
      clause: '5, Annex B',
      applicability: { requires: ['isElectronic'] },
      params: {},
      mvp: false,
    },
    {
      code: 'SPAN_STABILITY',
      evaluator: 'spanStability@1',
      title: 'Span stability',
      clause: '5.4, Annex B',
      applicability: { requires: ['isElectronic'] },
      params: {},
      mvp: false,
    },
    {
      code: 'MODULE_COMPAT',
      evaluator: 'moduleCompat@1',
      title: 'Compatibility of modules',
      clause: 'Annex F',
      applicability: { requires: ['modular'] },
      params: {},
      mvp: false,
    },
  ],

  limits: {
    eFormMultipliers: [1, 2, 5],
    auxiliaryIndication: {
      allowedClasses: ['I', 'II'],
      eMustBePowerOfTenInKg: true,
      maxDToERatio: 10,
    },
    initialZeroSettingMaxPct: '20',
    zeroTrackingCombinedMaxPct: '4',
    zeroSettingAccuracyE: '0.25',
    zeroTrackingRateMaxEPerSec: '0.5',
    discriminationExtraD: '1.4',
    repeatability: { maxLoadKgForTenReadings: '1000', readingsHigh: 10, readingsLow: 3 },
    tareAccuracyE: '0.25',
    tiltNoLoadMaxE: '2',
    warmupTimesMin: [0, 5, 15, 30],
    warmupZeroMaxE: '0.25',
    tempNoLoad: { I: { maxE: '1', perC: 1 }, default: { maxE: '1', perC: 5 } },
    creepTimesMin: [0, 5, 15, 30],
    creep30MinMaxE: '0.5',
    creep15to30MaxE: '0.2',
    creepExtendedTimeMin: 240,
    zeroReturnMaxE: '0.5',
    durability: { maxLoadKg: '100', eligibleClasses: ['II', 'III', 'IIII'] },
    disturbanceMaxIndicationChangeE: '1',
    spanStabilityMinE: '0.5',
    spanStabilityMpeFraction: '0.5',
    powerSupply: { highPct: '10', lowPct: '-15' },
    standardsAdequacyDivisor: 3,
    substitution: {
      fullSharePct: '50',
      reducedSharePct: '35',
      reducedRepeatabilityMaxE: '0.3',
      minimalSharePct: '20',
      minimalRepeatabilityMaxE: '0.2',
    },
    suspectReadingMpeMultiple: '3',
    deltaLStepFractionOfE: '0.1',
  },

  verification: {
    verifiedBy: null,
    verifiedAt: null,
    source: 'OIML R 76-1:2006 PDF, oiml.org (test fixture copy)',
  },
};

let cached: Rulepack | undefined;

/** The fixture rule pack, validated once and memoised. */
export function getRulepack(): Rulepack {
  cached ??= loadRulepack(RAW_RULEPACK);
  return cached;
}
