/**
 * Shared column builders (implementation.md §5 conventions).
 *
 * uuid PKs are v7 (time-ordered), generated by the `uuid_generate_v7()`
 * Postgres function installed in `migrations/0001_extensions_and_functions.sql`
 * — not by the application — so every writer (Drizzle, a seed script, `psql`)
 * gets the same id shape.
 */
import { sql } from 'drizzle-orm';
import type { PgColumn } from 'drizzle-orm/pg-core';
import { check, integer, timestamp, uuid } from 'drizzle-orm/pg-core';

export function idColumn() {
  return uuid('id')
    .primaryKey()
    .default(sql`uuid_generate_v7()`);
}

export function fkUuid(name: string) {
  return uuid(name);
}

export const createdAtColumn = () =>
  timestamp('created_at', { withTimezone: true }).notNull().defaultNow();

export const updatedAtColumn = () =>
  timestamp('updated_at', { withTimezone: true }).notNull().defaultNow();

export const rowVersionColumn = () => integer('row_version').notNull().default(1);

/** A `CHECK (column IN (...))` constraint over a fixed, compile-time set of strings. */
export function enumCheck(name: string, column: PgColumn, values: readonly string[]) {
  return check(
    name,
    sql`${column} in (${sql.join(
      values.map((value) => sql`${value}`),
      sql`, `,
    )})`,
  );
}
