'use client';

import {
  type Dec,
  type InstrumentMetrology,
  planCreep,
  planDiscrimination,
  planEccentricity,
  planRepeatability,
  planTemperatureSequence,
  planTests,
  planWeighingLoads,
} from '@tula/engine';
import { OIML_R76_1_2006 } from '@tula/rulepacks';
import { useMemo, useState } from 'react';
import { ReasonDialog } from '@/components/forms/ReasonDialog';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';

/** A short, human-readable summary of the planned params — display only; the server computes the stored ones. */
function describeParams(code: string, spec: InstrumentMetrology): string | null {
  const rulepack = OIML_R76_1_2006;
  const kg = (v: Dec) => `${(Number(v) / 1000).toLocaleString()} kg`;
  switch (code) {
    case 'WEIGHING': {
      const ranges = planWeighingLoads(spec, rulepack);
      return ranges.map((r) => r.ascending.map((row) => kg(row.L)).join(', ')).join(' | ');
    }
    case 'ECCENTRICITY': {
      const p = planEccentricity(spec);
      return `${kg(p.load)} at ${p.positions.length} positions`;
    }
    case 'REPEATABILITY': {
      const p = planRepeatability(spec, rulepack);
      return `${p.loads.map(kg).join(', ')} — ${p.readingsPerSeries} readings each`;
    }
    case 'DISCRIMINATION': {
      const p = planDiscrimination(spec, rulepack);
      return `${p.loads.map(kg).join(', ')} — extra load ${p.extraLoad} g`;
    }
    case 'CREEP': {
      const p = planCreep(spec, rulepack);
      return `${kg(p.load)} at ${p.scheduleMin.join('/')} min`;
    }
    case 'TEMP_STATIC':
    case 'TEMP_NO_LOAD': {
      const p = planTemperatureSequence(spec);
      return `${p.sequenceC.join(' → ')} °C`;
    }
    default:
      return null;
  }
}

function TestRow({
  title,
  clause,
  applicable,
  reason,
  paramsSummary,
  override,
  onMarkNa,
  onClearNa,
}: {
  title: string;
  clause: string;
  applicable: boolean;
  reason: string;
  paramsSummary: string | null;
  override: string | undefined;
  onMarkNa: () => void;
  onClearNa: () => void;
}) {
  const effectivelyApplicable = applicable && !override;
  return (
    <div className="flex items-start justify-between gap-4 border-b border-border py-3 last:border-0">
      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-2">
          <span className="tabular text-xs text-muted-foreground">{clause}</span>
          <span className="text-sm font-medium">{title}</span>
          <Badge variant={effectivelyApplicable ? 'default' : 'outline'}>
            {effectivelyApplicable ? 'Applicable' : 'N/A'}
          </Badge>
        </div>
        <p className="mt-0.5 text-sm text-muted-foreground">
          {override ? `Marked N/A: ${override}` : reason}
        </p>
        {effectivelyApplicable && paramsSummary ? (
          <p className="tabular mt-0.5 text-xs text-muted-foreground">{paramsSummary}</p>
        ) : null}
      </div>
      {applicable ? (
        <Button type="button" variant="ghost" size="sm" onClick={override ? onClearNa : onMarkNa}>
          {override ? 'Undo' : 'Mark N/A'}
        </Button>
      ) : null}
    </div>
  );
}

/**
 * Step 4 (implementation.md §7.5): "Test plan — every catalog test listed
 * with applicability and reason ... Marking a test N/A requires a reason."
 * Runs the same `planTests`/`planWeighingLoads`/etc. the server does at
 * submit time, purely for display — the authoritative plan is generated by
 * `submitEvaluationAction`, not read back from here.
 */
export function Step4TestPlan({
  spec,
  overrides,
  onOverridesChange,
}: {
  spec: InstrumentMetrology;
  overrides: Record<string, string>;
  onOverridesChange: (next: Record<string, string>) => void;
}) {
  const plannedTests = useMemo(() => planTests(spec, OIML_R76_1_2006), [spec]);
  const [naDialogCode, setNaDialogCode] = useState<string | null>(null);

  return (
    <div className="space-y-1">
      {plannedTests.map((test) => (
        <TestRow
          key={test.code}
          title={test.title}
          clause={test.clause}
          applicable={test.applicable}
          reason={test.reason}
          paramsSummary={test.applicable ? describeParams(test.code, spec) : null}
          override={overrides[test.code]}
          onMarkNa={() => setNaDialogCode(test.code)}
          onClearNa={() => {
            const next = { ...overrides };
            delete next[test.code];
            onOverridesChange(next);
          }}
        />
      ))}

      <ReasonDialog
        open={naDialogCode !== null}
        title="Mark test not applicable"
        description="This overrides the engine's default applicability for this evaluation only."
        confirmLabel="Mark N/A"
        onConfirm={(reason) => {
          if (naDialogCode) onOverridesChange({ ...overrides, [naDialogCode]: reason });
          setNaDialogCode(null);
        }}
        onCancel={() => setNaDialogCode(null)}
      />
    </div>
  );
}
